version: "3.7"
services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    command: [ "/bin/bash", "-c", "nginx -g 'daemon off;'" ]
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/cert:/etc/nginx/cert
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./blog:/usr/share/blog
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: [ "CMD", "curl", "http://localhost" ]
      interval: 60s
      timeout: 5s
      retries: 5
    restart: always
  autoheal:
    image: willfarrell/autoheal:1.2.0
    container_name: autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
